### ISSUE TITLE
Error! post.getUser is not a function - Chapter 4

### ISSUE THREAD

**Issue by nanoby7e** [PacktPublishing/Full-Stack-Web-Development-with-GraphQL-and-React-Second-Edition#7]
Hello!
I am running into an issue, where when I am at the end of Chapter 4, and I run my client and server, my web application loads. I can see my feed and chats trying to fetch the data, however I am seeing the following error in my browser:

`Error! post.getUser is not a function post.getUser is not a function`

I have spent the last few days troubleshooting, and am completely unable to get anything to load into my browser.  My full console log error is:

```
index.js:29 Uncaught (in promise) Error: post.getUser is not a function
post.getUser is not a function
    at new ApolloError (index.js:29:1)
    at QueryManager.js:610:1
    at both (asyncMap.js:16:46)
    at asyncMap.js:9:57
    at new Promise (<anonymous>)
    at Object.then (asyncMap.js:9:1)
    at Object.next (asyncMap.js:17:1)
    at notifySubscription (module.js:132:1)
    at onNotify (module.js:176:1)
    at SubscriptionObserver.next (module.js:225:1)
```

I have made sure that my resolvers.js and schema.js in src/server/services/graphql/, as well as all other files, are correct on my machine. I see the function in resolvers.js with the return statement using post.getUser:

```
const resolvers = {
    Post: {
      user(post, args, context) {
        return post.getUser();
      },
    },
```

I am not to familiar with Apollo/GraphQL, and am at the end of my troubleshooting abilities. Is there anyone that might be able to provide some more insight into this error?

Edit:

I should have noted, that I do see statements hit my terminal when the web page loads:

```
Executing (default): SELECT `User`.`id`, `User`.`avatar`, `User`.`username`, `User`.`createdAt`, `User`.`updatedAt`, `users_chats`.`createdAt` AS `users_chats.createdAt`, `users_chats`.`updatedAt` AS `users_chats.updatedAt`, `users_chats`.`ChatId` AS `users_chats.ChatId`, `users_chats`.`UserId` AS `users_chats.UserId` FROM `Users` AS `User` INNER JOIN `users_chats` AS `users_chats` ON `User`.`id` = `users_chats`.`UserId` AND `users_chats`.`ChatId` = 1;
Executing (default): SELECT `id`, `text`, `userId`, `chatId`, `createdAt`, `updatedAt`, `ChatId` FROM `Messages` AS `Message` WHERE `Message`.`ChatId` = 1 ORDER BY `Message`.`id` DESC LIMIT 1;
Executing (default): SELECT `id`, `text`, `createdAt`, `updatedAt` FROM `Posts` AS `Post` ORDER BY `Post`.`createdAt` DESC LIMIT 0, 10;
```

**Comment by nanoby7e** [comment]
I have figured it out. This was because I did not have the proper files in the src/server/models directory.
